### PR TITLE
Refactoring2

### PR DESCRIPTION
**Pull request by uidev547**
This included 
1. the removal of the duplicated code ( html / css / js )
2. created pages with jekyll templates and includes 
3. started with client js library
4. updated content from Rajani for about page.

cc @hashd , @ScrapCodes 
Thanks
Kiran

### CODE REVIEW

**Comment by hashd** [comment]
Thats a lot in one pull request. @ScrapCodes lets discuss about this tomorrow

**Comment by ScrapCodes** [comment]
@hashd Can I go ahead and merge this ? If it works okay. We can fix if there are other things later.

**Comment by ScrapCodes** [comment]
Can you please change the default ES URL to `http://labs.imaginea.com/kodebeagle`

**Comment by ScrapCodes** [comment]
Can you remove unneeded images ?

**Comment by ScrapCodes** [comment]
I hope this is the last time we are merging a lot of commits in one PR.

**Comment by uidev547** [comment]
yes this should be the last one.

**Pull request closed without merging**
