### PR TITLE
Update htmls for BetterDocs

### PR DESCRIPTION
**Pull request by uidev547**
Hi,
I have committed the new html pages and folder structre for BetterDocs.
Rewritten the existing application using Angular, bootstrap with three different themes.
 
changes made .
1. created less files for css
2. created gulp tasks for
    * less to css conversion
    * combine all js files to single minified  js file
    * generation of  minified css file.
3. developer version of page demov1-dev.html
4. production version of page demov1.html
5. used Angular as js library for the application ( ignored jquery and Handlebarjs libraries )
6. used less bootstarp frame work as css library.
*production usage file: http://uidev547.github.io/BetterDocs/demov1.html
 developer usage file: http://uidev547.github.io/BetterDocs/demov1-dev.html

Thanks
Kiran

### CODE REVIEW

**Comment by hashd** [comment]
Great work!

Couple of comments at the moment:
- Search bar can have white as the background to make it the brightest part of the screen
- Search bar should only have the cross icon when there is some content in the input box

**Comment by ScrapCodes** [comment]
Thanks for your PR @uidev547. It sure is a good UI. I had one question, Why is the code change so huge (+127,887 −0)?

**Comment by uidev547** [comment]
@ScrapCodes Hi I did not used the existing files. I have created new files and folders to create the application.
couple of reasons.
  1. used bootstrap files less files
  2. used angular libraries and new updated ace editor version
  3. used the less framework for css. 
  4. again all the development version of code will have production version of files (like compressed js and css)

@hashd : I'll look in to the comments provided by you. Thanks.

**Comment by ScrapCodes** [comment]
ahh, got it !

Few more questions,

1) Can we afford to remove all external libraries, somehow fetch them from cdn at the point first time the page is loaded. ? I am sure you must have considered it, I want to understand this.
2) Can we afford to do away the dev, from this Pull request ? you can keep it in your repo though.

**Comment by uidev547** [comment]
for point 1 I have some clarification to load the files from cdn. so right now I am not implemented to load the files from cdn. (as in production version all the files will be concatenated and minified to a single file.)

i not able to move this directly from pullRequest to dev. do i need to create a new ticket and close this icket?

**Comment by ScrapCodes** [comment]
You can push new commits to the same PR, should not be a problem.

**Comment by PiyushMishra** [comment]
Where is the configuration for Elasticsearch URL.

**Comment by ScrapCodes** [comment]
Piyush means this http://imaginea.github.io/BetterDocs/demo.html#modal

**Comment by uidev547** [comment]
@PiyushMishra fixed please verify.

**Comment by ScrapCodes** [comment]
I was just trying it out, the searching is not working with no error on display.

**Comment by uidev547** [comment]
@ScrapCodes , Thanks There was a script error and now it is fixed.

**Comment by ScrapCodes** [comment]
I can not get an alternate elastic search URL to work + the error displayed is not informative at all. All it says is ERROR.

**Comment by uidev547** [comment]
this could because of "CROP". is n't it working with default settings?

**Comment by uidev547** [comment]
As per the suggestions now all the external libraries are loading from the cdns. Please check.

**Comment by ScrapCodes** [comment]
Can you please also change "Better Docs" -> "Kode Beagle".

**Comment by hashd** [comment]
Just a comment, center aligned text is generally hard to read/follow, can't we have it left aligned and spacing justified

**Comment by uidev547** [comment]
i have updated the above comments.
@ScrapCodes : do need to change the http://labs.imaginea.com/betterdocs to http://labs.imaginea.com/kodebeagle ?

**Comment by uidev547** [comment]
latest checkins has 
1. added a filter for the contributer list (to remove gitter-badge and waffle-iron)
2. remove the index.md and created index.html
3. removed the dev version of css and build version of js
  i.e less to css will have the compressed css files
  and no minification of js ( non minified js files will be loaded in production as it is ).

**Comment by ScrapCodes** [comment]
Thanks, do you think it is good to go ?

Prashant Sharma

**Comment by uidev547** [comment]
yes

**Comment by ScrapCodes** [comment]
Great Thanks ! I just merged it.

**Pull request closed without merging**
