### PR TITLE
[docs] #652 Fix hyperlinks in README.md

### PR DESCRIPTION
**Pull request by asgs**
Fixed Markdown snippets for hyperlinks.

### CODE REVIEW

**Comment by asgs** [comment]
The builds are failing because of an SSL error happening while downloading the IJ Scala plugin. How do we retry the build?

**Comment by minidoc** [comment]
Thanks for the edits. 
You can meet with @keerath  today when you are in.

**Comment by keerath** [comment]
@asgs Please follow the commit message convention refer other commit messages

**Comment by keerath** [comment]
@asgs also please create an issue for every pull request that you raise.

**Comment by asgs** [comment]
Fixes #652 
Closes #649

**Pull request merged**
