### PR TITLE
[idea] #396 Fixed assertion error on windows when file opened 

### LINKED ISSUE #396: Fix assertion error on windows when file is opened from project tree

### PR DESCRIPTION
**Pull request by keerath**
…oject tree

fixes #396

### CODE REVIEW

**Comment by keerath** [comment]
@ScrapCodes PTAL..!!

**Comment by ScrapCodes** [comment]
It is failing because you have findbugs issues.

**Comment by ScrapCodes** [comment]
Looks good. Did you test it on windows ?

**Comment by keerath** [comment]
@ScrapCodes  yes i did ..!!

**Pull request merged**
