### PR TITLE
[idea] #292 Fixed text movement and increased horizontal space between labels.

### LINKED ISSUE #252: Link alignment and behaviour
* Can the links be positioned appropriately? 
* Need to distinguish the on-click behaviours between the two links.

*Screenshot contains some written text*
screen shot 2015-07-06 at 13 04 43

### LINKED ISSUE #292: On hover bold causes text to shift in "top" tab.
caused by #268

### PR DESCRIPTION
**Pull request by ScrapCodes**
Also fixes #252
fixes #292

We have chosen center align with increased horizontal gaps to 4 times than what it was.

### CODE REVIEW

**Comment by ScrapCodes** [comment]
@prudhvije Please review my PR !

**Comment by prudhvije** [comment]
@ScrapCodes  Since this PR removes bold #292 is fixed. But #252 issue demands more space or this is enough? if not LGTM.

**Comment by ScrapCodes** [comment]
Yes it demands more space, infact we need a layout manager that lets you set different alignment for each component. I don't know of it.

**Comment by prudhvije** [comment]
Even I'm stuck there only. Anyhow merge it for now. It's better than previous one.

**Comment by ScrapCodes** [comment]
merged

**Pull request closed without merging**
