### PR TITLE
Updated search page, about page added terms and conditions

### PR DESCRIPTION
**Pull request by uidev547**

### CODE REVIEW

**Comment by ScrapCodes** [comment]
WOW! A lot of "a" commit messages ! If you do not want to give a commit message you can use `git rebase -i` and squash them.

Is this PR same as http://uidev547.github.io/BetterDocs/ ? If so, I will let @Shiti comment too.

**Comment by ScrapCodes** [comment]
Looks like About page is still work in progress.

We also have a mailing list kodebeagle@googlegroups.com, we can use it as email for contact us and report issues should point to github issues.

**Comment by uidev547** [comment]
I was thinking till now "git commi -ma" is same as "git commit --amend" :-). 
this branch is the latest branch. 
as suggested by Dominic email address:'mailto:opensource@imaginea.com' and report issues link to 'github issues page'. let me know if any changes required. (these changes are not there in http://uidev547.github.io/BetterDocs/ but in this branch)

**Comment by Shiti** [comment]
I think u can squash commits with the same description so that its easier to see the changes. also, the last few commit messages are just `a`.

**Comment by minidoc** [comment]
@ScrapCodes The about page is work in progress because it is still awaiting content inputs from the team. Content like statistics, upcoming features, some good description on the different topics etc are still awaited. Can you work on these?

**Comment by ScrapCodes** [comment]
I am going to merge this now, All commits with no reference to issues on github will be squashed to form one big commit. @minidoc and @hashd are you okay with these changes ?

As a side note, merging it does not mean we will release it to public. It will be accessible via imaginea.github.io/KodeBeagle Only.

**Comment by ScrapCodes** [comment]
I think since you added not implemented yet component in this, I guess it is best to hold on for the moment. I will let you ping me once the PR is ready to be looked at again ?

**Pull request closed without merging**
